version: '3'

services:
  poe-to-gpt:
    image: ghcr.io/formzs/poe-to-gpt:latest
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "3700:3700"
    env_file:
      - .env
    restart: unless-stopped